### ISSUE TITLE
Add TO DO

### ISSUE THREAD

**Issue by ghost** [denosaurs/algebra#1]
# TO DO list / roadmap 

Hi! I li liked this project, but I can't know if the development process is up to date.
Сould you please add а dev. process like that:

![Screenshot_1](https://user-images.githubusercontent.com/75129392/109644097-65513b80-7b98-11eb-937a-48376a7ad57f.png)

thanks

**Comment by eliassjogreen** [comment]
Hi, this project is very WIP and maintained by @filipporeds. He is quite busy at the moment but may be able to provide a TODO for this project.
